using Newtonsoft.Json;
using System.Runtime.Serialization;
using Identifier = string;

namespace bsp4csharp.Protocol;

/// <summary>
/// Class which represents parameter sent with window/logMessage requests.
///
/// See the <see href="https://microsoft.github.io/language-server-protocol/specifications/base/0.9/specification/#logMessageParams">Base Protocol specification</see> for additional information.
/// </summary>
[DataContract]
public class LogMessageParams
{
    /// <summary>
    /// Gets or sets the type of message.
    /// </summary>
    [DataMember(Name = "type")]
    public MessageType MessageType { get; set; }

    /// <summary>
    /// Gets or sets the message.
    /// </summary>
    [DataMember(Name = "message")]
    public required string Message { get; set; }

    /** Unique id of the task with optional reference to parent task id */
    [DataMember(Name = "taskId")]
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public TaskId? TaskId { get; set; }

    /** A unique identifier generated by the client to identify this request. */
    [DataMember(Name = "originId")]
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public Identifier? OriginId { get; set; }
}