using System.Runtime.Serialization;

namespace bsp4csharp.Protocol;

[DataContract]
public record SourceItem
{
    /** <summary>
    * Either a text document or a directory. A directory entry must end with a forward
    * slash "/" and a directory entry implies that every nested text document within the
    * directory belongs to this source item.
    * </summary>
    **/
    [DataMember(Name = "uri")]
    public required Uri Uri { get; init; }

    /** <summary>
     * Type of file of the source item, such as whether it is file or directory.
     * </summary>
     **/
    [DataMember(Name = "kind")]
    public required SourceItemKind Kind { get; init; }

    /** <summary>
     * Indicates if this source is automatically generated by the build and is not
     * intended to be manually edited by the user.
     * </summary>
     **/
    public bool Generated { get; init; }
}

public enum SourceItemKind
{
    File = 1,
    Directory = 2,
}