using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace bsp4csharp.Protocol;

[DataContract]
public class TestCaseDiscoveryParams
{
    /** A sequence of build targets to compile. */
    [DataMember(Name="targets")]
    public BuildTargetIdentifier[] Targets { get; set; } = [];

    /** A unique identifier generated by the client to identify this request.
    * The server may include this id in triggered notifications or responses. */
    [DataMember(Name="originId")]
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)] 
    public string? OriginId { get; set; }
}